### ISSUE TITLE
PageManager.Current should be refactored

### ISSUE THREAD

**Issue by JasonRawlins** [CraftingBytes/BasePageObjectModel#1]
It's currently initializing everything including Chrome. Instead it should do page initialization only and perhaps have a second method the reinitialize Chrome.

**Comment by Foovanadil** [comment]
And the method to init the drive should probably be abstract and allow the caller to specify the driver they want to use.

**Comment by Foovanadil** [comment]
This is simplified in v 1.2.0.0

Chrome driver is the only thing initialized in in this call. You can override Initialize to control what driver is used and when it is used.
